Add background/overlay imagery layer info button
MarcusWolschon/osmeditor4android pull request #1359
Opened 2021-03-17 09:35 UTC by zedlabs

2021-03-17 11:17 UTC, simonpoole requested changes
Looks good, some minor nitpicks are listed inline below.

2021-03-17 11:17 UTC, simonpoole commented on src/main/java/de/blau/android/dialogs/ImageryListAdapter.java
> +    public void addItemClickListener(OnInfoClickListener listener) {
As above: consistent naming, javadoc and annotations.

2021-03-17 11:17 UTC, simonpoole commented on src/main/java/de/blau/android/dialogs/Layers.java
> +        adapter.addItemClickListener(this);
While a bit a matter of taste, I would have simply provided the listener as a lambda here, so something like

```
      adapter.addItemClickListener((String id) -> {
            TileLayerSource l = TileLayerSource.get(getContext(), id, true);
            if (l != null) {
                LayerInfo f = new ImageryLayerInfo();
                f.setShowsDialog(true);
                Bundle args = new Bundle();
                args.putSerializable(ImageryLayerInfo.LAYER_KEY, l);
                f.setArguments(args);
                LayerInfo.showDialog(getActivity(), f);
            }
        });
```

2021-03-17 11:17 UTC, simonpoole commented on src/main/java/de/blau/android/dialogs/Layers.java
> +
See above. as we might want to rip the whole imagery selection dialog out and put it in a separate class one day, I would tend to keep everything together.

2021-03-17 11:17 UTC, simonpoole commented on src/main/res/layout/imagery_layer_list_item.xml
> +        android:src="?attr/menu_information"
I suspect ?attr/information_small would look better here (it's a slightly smaller version of the same icon). 

The other thing is that when I tested in an emulator there was some overlap between the text and the (i) in some cases as  the text wasn't wrapping early enough, could you check that?

2021-03-17 13:03 UTC, zedlabs commented
made the changes but the icon seems to small
![Screenshot (163)](https://user-images.githubusercontent.com/32540498/111471711-3073e580-874f-11eb-841f-57b01915fd9c.png)

2021-03-17 16:06 UTC, simonpoole commented
Hmm, do you have font scaling turned on? For me (standard emulator settings), it looks like 

![Screenshot_1615996931](https://user-images.githubusercontent.com/1011860/111499006-c9e8ca80-8742-11eb-8560-9c89ac801d4d.png)

While one could still argue that the button is too small (at least for me it doesn't seem so in practical terms on a real device, and I have not so good eyesight), the proportions would seem to fit better.

2021-03-17 16:18 UTC, zedlabs commented
Yeah, I forgot to turn scaling off.
It looks fine on the default font size

2021-03-17 16:48 UTC, simonpoole approved these changes

2021-03-17 16:53 UTC, simonpoole commented
Thanks for the contribution. 

We're just before a release, which will then be on its own branch.  Potentially I'll ask you to rebase immediately after that has happend (the only expected changes are translations and documentation) so that I can cleanly merge this.

2021-03-27 17:28 UTC, simonpoole commented
@zedlabs can you rebase this on master? Thanks.

2021-03-28 05:31 UTC, zedlabs commented
done @simonpoole

2021-03-28 10:03 UTC, merged