filter background layer by terrain
MarcusWolschon/osmeditor4android pull request #1360
Opened 2021-03-19 10:28 UTC by zedlabs

adds radio button to filter background imagery layers by terrain
fixes #1357

2021-03-30 11:31 UTC, simonpoole requested changes
This really needs a short test of switching between the categories. See https://github.com/MarcusWolschon/osmeditor4android/blob/master/src/androidTest/java/de/blau/android/layer/LayerDialogTest.java for some examples, in particular backgroundLayerTest for getting the dialog.

I would simply switch between the three possible states and check the displayed content.

2021-03-31 17:17 UTC, zedlabs commented
@simonpoole please take a look at this test, I'm not really sure if this was the expected result

2021-04-03 09:33 UTC, simonpoole requested changes
Running the test on an Emulator I noticed an UI glitch that needs to be looked at, see

![grafik](https://user-images.githubusercontent.com/1011860/113474434-3caab300-9470-11eb-90f2-9fdea22cbc39.png)

![grafik](https://user-images.githubusercontent.com/1011860/113474455-58ae5480-9470-11eb-8fea-249f4b77b760.png)

See the inline comments the other small issues.

2021-04-03 09:33 UTC, simonpoole commented on src/androidTest/java/de/blau/android/TestUtils.java
> +    public static boolean findInParentList(String[] parentList, String child) {
Annotations please

2021-04-03 09:33 UTC, simonpoole commented on src/androidTest/java/de/blau/android/layer/LayerDialogTest.java
> +        assertTrue(TestUtils.clickText(device, false, main.getString(R.string.menu_layers_add_backgroundlayer), true, false));
After this you should add an, not asserted, click on the OK button to click away the Tip dialog if it is displayed (which will happen if you are just running this test), see the backgroundLayer test.

2021-04-03 09:33 UTC, simonpoole commented on src/androidTest/java/de/blau/android/layer/LayerDialogTest.java
> +        UiObject2 stamenTerrain = TestUtils.findObjectWithText(device, false, "Stamen Terrain", 1000);
This is a bit brittle as there is no guarantee that the Stamen Terrain layer is available (in general you can only rely on the couple of entries that are Vespucci specific to be around). Best simply add a layer of the Terrain category with TileLayerSource.addOrUpdateCustomLayer at the beginning of the test with an unique name and check if that then turns up.

2021-04-14 07:40 UTC, zedlabs commented
@simonpoole Please take a look

2021-04-14 16:24 UTC, simonpoole reviewed
Could you rebase on master? This is probably good to merge, and it makes things simpler to review too. Thanks.

2021-04-14 17:19 UTC, zedlabs commented
@simonpoole done, also please have a look at #1363

2021-04-14 19:57 UTC, merged

2021-04-14 19:59 UTC, simonpoole commented
Thanks. https://github.com/MarcusWolschon/osmeditor4android/pull/1363 in due course.