Compute pseudo accuracy from NMEA
MarcusWolschon/osmeditor4android pull request #1485
Opened 2021-11-09 02:40 UTC by gdt

The standard NMEA sentences do not contain an estimate of accuracy,
and thus Vespucci does not show an accuracy circle when using NMEA.
When surveying with RTK, it's very important to know if the device is
in normal mode vs RTK-float vs RTK-fixed.

Therefore, extract the fix type from GGA, and estimate accuracy,
picking 1m for float and 0.1m for fixed, and 5m (differential) or 10m
(autonomous) scaled by HDOP.

Tested with an F9P.

2021-11-09 08:52 UTC, simonpoole requested changes
This looks good, but some stylistic nit picks:

- please use a switch statement instead of multiple if ... else
- define constants for the fix type and the accuracy values

for a *logic* pov, move line 164 to after the new code, as this is the flag that indicates that we have parsed everything and the position should be updated.

You can simply force push any changes over this commit

2021-11-13 00:35 UTC, gdt commented
Thanks for the review comments.   I think I've addressed them and some further logic cleanup, and live tested again with an F9P.  I'm new to Java, and happy to make any other changes you'd like.

2021-11-13 10:19 UTC, simonpoole commented
Merged with https://github.com/MarcusWolschon/osmeditor4android/commit/c1787f99458856002f5496428568bfbc605345ae

Thanks!

General note, pull requests should always (special cases excepted) be re-based on the current HEAD of the master branch, this gives a nice linear commit history and makes it easier to understand when what was committed. You can see that here https://github.com/gdt/osmeditor4android/tree/feature.fauxAccuracy which indicates that have been commits to master which haven't been reflected in your branch. 

Now I simply did that locally here this time (that's why I'm closing the PR manually), but in general it is better if the person creating the PR does it, because essentially it means your copy of the repository is out of date and something may have changed that actually has a bearing on your commits.

2021-11-13 10:19 UTC, closed without merging

2021-11-13 16:33 UTC, gdt commented
Thanks - I did that the first time and forgot while addressing the review comments.  Will try to remember next time.